"use client"

import * as React from "react"
import { useBuilderStore } from "@/store/useBuilderStore"
import { Copy, Check, Terminal } from "lucide-react"

export function CodeViewer() {
  const { strategyDSL } = useBuilderStore()
  const [copied, setCopied] = React.useState(false)

  const generatePythonCode = () => {
    if (!strategyDSL) {
      return `# No strategy configured yet.
# Use the AI Copilot on the left to generate a strategy.
# Example: "Buy TSLA when RSI drops below 30"
`;
    }

    const { name, instruments, entryConditions, exitConditions, action, riskParameters } = strategyDSL;
    const symbol = instruments?.[0]?.symbol || 'AAPL';
    
    let pythonCode = `"""
Strategy: ${name}
Auto-generated by AlgoText.ai Quant Engine
"""
import alpaca_trade_api as tradeapi
import pandas as pd
import numpy as np
import time

# Initialize Alpaca API
api = tradeapi.REST('YOUR_API_KEY', 'YOUR_SECRET_KEY', base_url='https://paper-api.alpaca.markets')
symbol = '${symbol}'

def check_conditions(df):
    latest = df.iloc[-1]
    
    # Entry Conditions
`;
    
    if (entryConditions && entryConditions.length > 0) {
      entryConditions.forEach((cond, idx) => {
        let pyCond = `latest['${cond.left?.type}'] ${getOperator(cond.comparator)} ${cond.right}`;
        pythonCode += `    cond_entry_${idx} = ${pyCond}\n`;
      });
      pythonCode += `    entry_signal = ${entryConditions.map((_, i) => `cond_entry_${i}`).join(' and ')}\n`;
    } else {
      pythonCode += `    entry_signal = False\n`;
    }

    pythonCode += `\n    # Exit Conditions\n`;
    
    if (exitConditions && exitConditions.length > 0) {
      exitConditions.forEach((cond, idx) => {
        let pyCond = `latest['${cond.left?.type}'] ${getOperator(cond.comparator)} ${cond.right}`;
        pythonCode += `    cond_exit_${idx} = ${pyCond}\n`;
      });
      pythonCode += `    exit_signal = ${exitConditions.map((_, i) => `cond_exit_${i}`).join(' and ')}\n`;
    } else {
      pythonCode += `    exit_signal = False\n`;
    }

    pythonCode += `
    return entry_signal, exit_signal

def execute_trade(action, qty_percent):
    account = api.get_account()
    buying_power = float(account.buying_power)
    current_price = api.get_latest_trade(symbol).price
    
    qty = int((buying_power * (qty_percent / 100)) / current_price)
    
    if action == 'BUY':
        api.submit_order(
            symbol=symbol,
            qty=qty,
            side='buy',
            type='market',
            time_in_force='gtc'
        )
        print(f"Executed BUY for {qty} shares of {symbol}")
        
    elif action == 'SELL' or action == 'CLOSE_POSITION':
        api.close_position(symbol)
        print(f"Closed position for {symbol}")

def run_bot():
    print("Starting AlgoText Trading Bot...")
    while True:
        # Fetch latest market data
        bars = api.get_bars(symbol, tradeapi.TimeFrame.Minute, limit=100).df
        
        # Assume indicators are pre-calculated by a utility function
        # df = calculate_indicators(bars)
        df = bars # Placeholder
        
        entry_signal, exit_signal = check_conditions(df)
        
        position = None
        try:
            position = api.get_position(symbol)
        except:
            pass
            
        if entry_signal and not position:
            execute_trade('${action?.type || 'BUY'}', ${action?.quantityValue || 100})
            
        elif exit_signal and position:
            execute_trade('CLOSE_POSITION', 100)
            
        time.sleep(60) # Run every minute

if __name__ == "__main__":
    run_bot()
`;
    return pythonCode;
  }

  const getOperator = (comparator: string) => {
    switch (comparator) {
      case 'GREATER_THAN': return '>';
      case 'LESS_THAN': return '<';
      case 'EQUAL': return '==';
      case 'CROSSES_ABOVE': return '>';
      case 'CROSSES_BELOW': return '<';
      default: return '==';
    }
  }

  const code = generatePythonCode();

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="flex flex-1 flex-col border-t border-bg-border bg-white overflow-hidden shadow-[inset_0_2px_4px_rgba(0,0,0,0.02)]">
      <div className="flex h-[40px] shrink-0 items-center justify-between border-b border-bg-border bg-[#F8FAFC] px-4">
        <div className="flex items-center gap-2">
          <Terminal className="h-4 w-4 text-text-tertiary" />
          <span className="text-[12px] font-mono text-text-secondary">main.py (Alpaca Sandbox)</span>
        </div>
        <button 
          onClick={handleCopy}
          className="flex items-center gap-1.5 rounded-md px-2 py-1 text-[12px] text-text-tertiary hover:bg-black/5 hover:text-text-primary transition-colors"
        >
          {copied ? <Check className="h-3.5 w-3.5 text-accent-green" /> : <Copy className="h-3.5 w-3.5" />}
          {copied ? 'Copied' : 'Copy Code'}
        </button>
      </div>
      <div className="flex-1 overflow-auto p-4">
        <pre className="font-mono text-[13px] text-text-primary leading-relaxed">
          <code dangerouslySetInnerHTML={{ 
            __html: code
              .replace(/def (.*?)\(/g, '<span class="text-blue-600 font-medium">def</span> <span class="text-amber-600">$1</span>(')
              .replace(/return/g, '<span class="text-blue-600 font-medium">return</span>')
              .replace(/if|elif|else|while|and|not/g, '<span class="text-blue-600 font-medium">$&</span>')
              .replace(/True|False|None/g, '<span class="text-emerald-600 font-medium">$&</span>')
              .replace(/import/g, '<span class="text-blue-600 font-medium">import</span>')
              .replace(/#.*/g, '<span class="text-slate-400 italic">$&</span>')
              .replace(/('.*?')/g, '<span class="text-emerald-600">$1</span>')
              .replace(/"""([\s\S]*?)"""/g, '<span class="text-slate-400 italic">"""$1"""</span>')
          }} />
        </pre>
      </div>
    </div>
  )
}
