"use client"

import * as React from "react"
import { useBuilderStore } from "@/store/useBuilderStore"
import { Copy, Check, Terminal } from "lucide-react"
import { toast } from "sonner"

export type CodeLanguage = 'python' | 'pinescript' | 'nodejs';

export function CodeViewer() {
  const { strategyDSL } = useBuilderStore()
  const [copied, setCopied] = React.useState(false)
  const [language, setLanguage] = React.useState<CodeLanguage>('python')

  const getOperator = (comparator: string) => {
    switch (comparator) {
      case 'GREATER_THAN': return '>';
      case 'LESS_THAN': return '<';
      case 'EQUAL': return '==';
      case 'CROSSES_ABOVE': return '>';
      case 'CROSSES_BELOW': return '<';
      default: return '==';
    }
  }

  // Format indicator accessor string for Python pandas_ta
  const getPythonIndicatorCol = (ind: any) => {
    if (!ind || !ind.type) return "df['close']";
    const period = ind.parameters?.period || 14;
    switch (ind.type) {
      case 'PRICE': return "df['close']";
      case 'VOLUME': return "df['volume']";
      case 'EMA': return `df['EMA_${period}']`;
      case 'SMA': return `df['SMA_${period}']`;
      case 'RSI': return `df['RSI_${period}']`;
      case 'MACD': return "df['MACD_12_26_9']";
      case 'MACD_SIGNAL': return "df['MACDs_12_26_9']";
      case 'MACD_HISTOGRAM': return "df['MACDh_12_26_9']";
      case 'BOLLINGER_UPPER': return `df['BBU_${period}_2.0']`;
      case 'BOLLINGER_LOWER': return `df['BBL_${period}_2.0']`;
      case 'BOLLINGER_MIDDLE': return `df['BBM_${period}_2.0']`;
      case 'VWAP': return "df['VWAP']";
      case 'ATR': return `df['ATRr_${period}']`;
      case 'SUPERTREND': return `df['SUPERTd_${period}_3.0']`;
      case 'STOCHASTIC_K': return `df['STOCHk_${period}_3_3']`;
      case 'STOCHASTIC_D': return `df['STOCHd_${period}_3_3']`;
      case 'VOLUME_SMA': return `df['VOL_SMA_${period}']`;
      default: return `df['${ind.type}']`;
    }
  };

  // Format PineScript v5 indicator expression
  const getPineScriptExpr = (ind: any) => {
    if (!ind || !ind.type) return "close";
    const period = ind.parameters?.period || 14;
    switch (ind.type) {
      case 'PRICE': return "close";
      case 'VOLUME': return "volume";
      case 'EMA': return `ta.ema(close, ${period})`;
      case 'SMA': return `ta.sma(close, ${period})`;
      case 'RSI': return `ta.rsi(close, ${period})`;
      case 'MACD': return "ta.macd(close, 12, 26, 9)[0]";
      case 'MACD_SIGNAL': return "ta.macd(close, 12, 26, 9)[1]";
      case 'MACD_HISTOGRAM': return "ta.macd(close, 12, 26, 9)[2]";
      case 'BOLLINGER_UPPER': return `ta.bb(close, ${period}, 2)[0]`;
      case 'BOLLINGER_LOWER': return `ta.bb(close, ${period}, 2)[2]`;
      case 'BOLLINGER_MIDDLE': return `ta.bb(close, ${period}, 2)[1]`;
      case 'VWAP': return "ta.vwap(close)";
      case 'ATR': return `ta.atr(${period})`;
      case 'SUPERTREND': return `ta.supertrend(3, ${period})[0]`;
      case 'STOCHASTIC_K': return `ta.stoch(close, high, low, ${period})`;
      case 'VOLUME_SMA': return `ta.sma(volume, ${period})`;
      default: return `${ind.type.toLowerCase()}`;
    }
  };

  const generatePythonCode = () => {
    if (!strategyDSL) {
      return `# No strategy configured yet.\n# Use AI Copilot or Block Library to build your quant algorithm.\n`;
    }

    const { name, instruments, entryConditions, exitConditions, action, riskParameters } = strategyDSL;
    const symbol = instruments?.[0]?.symbol || 'BTC/USDT';
    const cleanSymbol = symbol.replace('/USDT', '');
    const stopLoss = riskParameters?.stopLossPercentage || 3.0;
    const takeProfit = riskParameters?.takeProfitPercentage || 6.0;
    const actionType = action?.type || 'BUY';
    const quantityVal = action?.quantityValue || 50;

    let code = `"""
Strategy: ${name}
Generated by Algorush Quantitative AI Engine
Stack: Python 3.10+, pandas_ta, Alpaca Trade API
"""
import alpaca_trade_api as tradeapi
import pandas as pd
import pandas_ta as ta
import numpy as np
import time

API_KEY = "YOUR_ALPACA_API_KEY"
SECRET_KEY = "YOUR_ALPACA_SECRET_KEY"
BASE_URL = "https://paper-api.alpaca.markets"

api = tradeapi.REST(API_KEY, SECRET_KEY, BASE_URL, api_version='v2')
SYMBOL = "${cleanSymbol}"

def calculate_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """Calculates quantitative technical indicators using pandas_ta."""
    df = df.copy()
    
    # Core price and volume indicators
    df['SMA_50'] = ta.sma(df['close'], length=50)
    df['EMA_50'] = ta.ema(df['close'], length=50)
    df['EMA_200'] = ta.ema(df['close'], length=200)
    df['RSI_14'] = ta.rsi(df['close'], length=14)
    
    # MACD (12, 26, 9)
    macd = ta.macd(df['close'], fast=12, slow=26, signal=9)
    if macd is not None:
        df = pd.concat([df, macd], axis=1)
        
    # Bollinger Bands (20, 2.0)
    bb = ta.bbands(df['close'], length=20, std=2.0)
    if bb is not None:
        df = pd.concat([df, bb], axis=1)
        
    # ATR & Volume SMA
    df['ATRr_14'] = ta.atr(df['high'], df['low'], df['close'], length=14)
    df['VOL_SMA_20'] = ta.sma(df['volume'], length=20)
    
    return df

def generate_signals(df: pd.DataFrame):
    """Evaluates multi-condition strategy logic on the latest market candle."""
    latest = df.iloc[-1]
    prev = df.iloc[-2]
    
    # --- ENTRY CONDITIONS ---
`;

    if (entryConditions && entryConditions.length > 0) {
      const entryCodeLines: string[] = [];
      entryConditions.forEach((cond, idx) => {
        const leftCol = getPythonIndicatorCol(cond.left);
        let rightExpr = '';
        if (typeof cond.right === 'object' && cond.right !== null && cond.right.type) {
          rightExpr = getPythonIndicatorCol(cond.right);
        } else {
          rightExpr = String(cond.right);
        }

        if (cond.comparator === 'CROSSES_ABOVE') {
          const prevLeftCol = leftCol.replace("df['", "prev['");
          const prevRightCol = rightExpr.includes("df['") ? rightExpr.replace("df['", "prev['") : rightExpr;
          code += `    cond_entry_${idx} = (latest['${leftCol.replace("df['", "").replace("']", "")}'] > ${rightExpr.replace("df['", "latest['")}) and (${prevLeftCol} <= ${prevRightCol})\n`;
        } else if (cond.comparator === 'CROSSES_BELOW') {
          const prevLeftCol = leftCol.replace("df['", "prev['");
          const prevRightCol = rightExpr.includes("df['") ? rightExpr.replace("df['", "prev['") : rightExpr;
          code += `    cond_entry_${idx} = (latest['${leftCol.replace("df['", "").replace("']", "")}'] < ${rightExpr.replace("df['", "latest['")}) and (${prevLeftCol} >= ${prevRightCol})\n`;
        } else {
          const op = getOperator(cond.comparator);
          code += `    cond_entry_${idx} = ${leftCol.replace("df['", "latest['")} ${op} ${rightExpr.replace("df['", "latest['")}\n`;
        }
        entryCodeLines.push(`cond_entry_${idx}`);
      });
      code += `    entry_signal = ${entryCodeLines.join(' and ')}\n`;
    } else {
      code += `    entry_signal = False\n`;
    }

    code += `\n    # --- EXIT CONDITIONS ---\n`;

    if (exitConditions && exitConditions.length > 0) {
      const exitCodeLines: string[] = [];
      exitConditions.forEach((cond, idx) => {
        const leftCol = getPythonIndicatorCol(cond.left);
        let rightExpr = '';
        if (typeof cond.right === 'object' && cond.right !== null && cond.right.type) {
          rightExpr = getPythonIndicatorCol(cond.right);
        } else {
          rightExpr = String(cond.right);
        }
        const op = getOperator(cond.comparator);
        code += `    cond_exit_${idx} = ${leftCol.replace("df['", "latest['")} ${op} ${rightExpr.replace("df['", "latest['")}\n`;
        exitCodeLines.push(`cond_exit_${idx}`);
      });
      const joinOp = exitConditions.some(c => c.logicalOperator === 'OR') ? ' or ' : ' and ';
      code += `    exit_signal = ${exitCodeLines.join(joinOp)}\n`;
    } else {
      code += `    exit_signal = False\n`;
    }

    code += `
    return entry_signal, exit_signal

def execute_orders(action_type: str, qty_percent: float):
    """Executes order on Alpaca API with risk controls."""
    account = api.get_account()
    equity = float(account.equity)
    price = float(api.get_latest_trade(SYMBOL).price)
    
    qty = max(1, int((equity * (qty_percent / 100)) / price))
    
    if action_type == 'BUY':
        print(f"[ORDER] Submitting BUY order for {qty} units of {SYMBOL}")
        api.submit_order(
            symbol=SYMBOL,
            qty=qty,
            side='buy',
            type='market',
            time_in_force='gtc'
        )
    elif action_type == 'SELL':
        print(f"[ORDER] Submitting SELL (Short) order for {qty} units of {SYMBOL}")
        api.submit_order(
            symbol=SYMBOL,
            qty=qty,
            side='sell',
            type='market',
            time_in_force='gtc'
        )
    elif action_type == 'CLOSE_POSITION':
        print(f"[ORDER] Closing position for {SYMBOL}")
        api.close_position(SYMBOL)

def run():
    print(f"Starting Quantitative Trading Bot for {SYMBOL}...")
    stop_loss_pct = ${stopLoss}
    take_profit_pct = ${takeProfit}
    
    while True:
        try:
            bars = api.get_bars(SYMBOL, tradeapi.TimeFrame.Minute, limit=200).df
            df = calculate_indicators(bars)
            entry_signal, exit_signal = generate_signals(df)
            
            position = None
            try:
                position = api.get_position(SYMBOL)
            except:
                pass
                
            if entry_signal and not position:
                execute_orders('${actionType}', ${quantityVal})
            elif exit_signal and position:
                execute_orders('CLOSE_POSITION', 100)
                
        except Exception as e:
            print(f"[ERROR] Engine loop exception: {e}")
            
        time.sleep(60)

if __name__ == "__main__":
    run()
`;
    return code;
  }

  const generatePineScriptCode = () => {
    if (!strategyDSL) return `//@version=5\n// No strategy configured yet.`;
    const { name, entryConditions, exitConditions, riskParameters } = strategyDSL;
    
    let code = `//@version=5\nstrategy("${name}", overlay=true, initial_capital=10000, default_qty_type=strategy.percent_of_equity, default_qty_value=50)\n\n`;
    
    code += `// --- ENTRY CONDITIONS ---\n`;
    if (entryConditions && entryConditions.length > 0) {
      entryConditions.forEach((cond, idx) => {
        const leftExpr = getPineScriptExpr(cond.left);
        let rightExpr = typeof cond.right === 'object' && cond.right !== null ? getPineScriptExpr(cond.right) : String(cond.right);

        if (cond.comparator === 'CROSSES_ABOVE') {
          code += `cond_entry_${idx} = ta.crossover(${leftExpr}, ${rightExpr})\n`;
        } else if (cond.comparator === 'CROSSES_BELOW') {
          code += `cond_entry_${idx} = ta.crossunder(${leftExpr}, ${rightExpr})\n`;
        } else {
          const op = getOperator(cond.comparator);
          code += `cond_entry_${idx} = ${leftExpr} ${op} ${rightExpr}\n`;
        }
      });
      code += `longCondition = ${entryConditions.map((_, i) => `cond_entry_${i}`).join(' and ')}\n\n`;
    } else {
      code += `longCondition = false\n\n`;
    }

    code += `// --- EXIT CONDITIONS ---\n`;
    if (exitConditions && exitConditions.length > 0) {
      exitConditions.forEach((cond, idx) => {
        const leftExpr = getPineScriptExpr(cond.left);
        let rightExpr = typeof cond.right === 'object' && cond.right !== null ? getPineScriptExpr(cond.right) : String(cond.right);
        const op = getOperator(cond.comparator);
        code += `cond_exit_${idx} = ${leftExpr} ${op} ${rightExpr}\n`;
      });
      const joinOp = exitConditions.some(c => c.logicalOperator === 'OR') ? ' or ' : ' and ';
      code += `exitCondition = ${exitConditions.map((_, i) => `cond_exit_${i}`).join(joinOp)}\n\n`;
    } else {
      code += `exitCondition = false\n\n`;
    }

    code += `if (longCondition)\n    strategy.entry("Long Entry", strategy.long)\n\n`;
    code += `if (exitCondition)\n    strategy.close("Long Entry")\n\n`;

    if (riskParameters && (riskParameters.stopLossPercentage || riskParameters.takeProfitPercentage)) {
      const sl = riskParameters.stopLossPercentage ? (riskParameters.stopLossPercentage / 100) : 0.03;
      const tp = riskParameters.takeProfitPercentage ? (riskParameters.takeProfitPercentage / 100) : 0.06;
      code += `// --- RISK MANAGEMENT (SL/TP) ---\n`;
      code += `strategy.exit("Bracket Exit", "Long Entry", stop=strategy.position_avg_price * (1 - ${sl}), limit=strategy.position_avg_price * (1 + ${tp}))\n`;
    }

    return code;
  }

  const generateNodeJSCode = () => {
    if (!strategyDSL) return `// No strategy configured yet.`;
    const { name, instruments, entryConditions, exitConditions } = strategyDSL;
    const symbol = instruments?.[0]?.symbol || 'BTC/USDT';
    
    let code = `/**\n * Strategy: ${name}\n * Auto-generated CCXT Node.js Trading Bot\n */\n`;
    code += `const ccxt = require('ccxt');\n\n`;
    code += `const exchange = new ccxt.binance({\n  apiKey: process.env.BINANCE_API_KEY,\n  secret: process.env.BINANCE_SECRET_KEY,\n  enableRateLimit: true,\n});\n\n`;
    code += `const SYMBOL = '${symbol}';\n\n`;
    
    code += `async function fetchIndicators() {\n`;
    code += `  const ohlcv = await exchange.fetchOHLCV(SYMBOL, '1m', undefined, 100);\n`;
    code += `  const closes = ohlcv.map(c => c[4]);\n`;
    code += `  const volumes = ohlcv.map(c => c[5]);\n\n`;
    code += `  const latestClose = closes[closes.length - 1];\n`;
    code += `  const latestVolume = volumes[volumes.length - 1];\n\n`;
    code += `  return { latestClose, latestVolume };\n}\n\n`;

    code += `async function run() {\n`;
    code += `  console.log("Starting CCXT Trading Engine for " + SYMBOL);\n`;
    code += `  setInterval(async () => {\n`;
    code += `    try {\n`;
    code += `      const data = await fetchIndicators();\n`;
    code += `      console.log(\`[TICK] \${SYMBOL} Price: \${data.latestClose}\`);\n`;
    code += `    } catch (e) {\n`;
    code += `      console.error("[ERROR] ", e.message);\n`;
    code += `    }\n`;
    code += `  }, 60000);\n}\n\nrun();`;
    
    return code;
  }

  const getCode = () => {
    if (language === 'python') return generatePythonCode();
    if (language === 'pinescript') return generatePineScriptCode();
    if (language === 'nodejs') return generateNodeJSCode();
    return "";
  }

  const code = getCode();

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    toast.success("Code copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="flex flex-1 flex-col border-t border-bg-border bg-white overflow-hidden shadow-[inset_0_2px_4px_rgba(0,0,0,0.02)]">
      <div className="flex h-[40px] shrink-0 items-center justify-between border-b border-bg-border bg-[#F8FAFC] px-4">
        <div className="flex items-center gap-2">
          <Terminal className="h-4 w-4 text-text-tertiary" />
          <select 
            value={language}
            onChange={(e) => setLanguage(e.target.value as CodeLanguage)}
            className="bg-transparent text-[12px] font-mono text-text-secondary focus:outline-none cursor-pointer hover:text-text-primary"
          >
            <option value="python">main.py (Alpaca / pandas_ta)</option>
            <option value="pinescript">strategy.pine (TradingView v5)</option>
            <option value="nodejs">index.js (Binance CCXT)</option>
          </select>
        </div>
        <button 
          onClick={handleCopy}
          className="flex items-center gap-1.5 rounded-md px-2 py-1 text-[12px] text-text-tertiary hover:bg-black/5 hover:text-text-primary transition-colors"
        >
          {copied ? <Check className="h-3.5 w-3.5 text-accent-green" /> : <Copy className="h-3.5 w-3.5" />}
          {copied ? 'Copied' : 'Copy Code'}
        </button>
      </div>
      <div className="flex-1 overflow-auto p-4">
        <pre className="font-mono text-[13px] text-text-primary leading-relaxed">
          <code dangerouslySetInnerHTML={{ 
            __html: code
              .replace(/def (.*?)\(/g, '<span class="text-blue-600 font-medium">def</span> <span class="text-amber-600">$1</span>(')
              .replace(/function (.*?)\(/g, '<span class="text-blue-600 font-medium">function</span> <span class="text-amber-600">$1</span>(')
              .replace(/return/g, '<span class="text-blue-600 font-medium">return</span>')
              .replace(/const|let|var|require|async|await/g, '<span class="text-blue-600 font-medium">$&</span>')
              .replace(/if|elif|else|while|and|or|not|strategy|strategy.entry|strategy.close|strategy.exit|strategy.long/g, '<span class="text-blue-600 font-medium">$&</span>')
              .replace(/True|False|None|true|false/g, '<span class="text-emerald-600 font-medium">$&</span>')
              .replace(/import/g, '<span class="text-blue-600 font-medium">import</span>')
              .replace(/#.*/g, '<span class="text-slate-400 italic">$&</span>')
              .replace(/\/\/.*/g, '<span class="text-slate-400 italic">$&</span>')
              .replace(/('.*?'|".*?")/g, '<span class="text-emerald-600">$1</span>')
              .replace(/"""([\s\S]*?)"""/g, '<span class="text-slate-400 italic">"""$1"""</span>')
              .replace(/\/\*\*([\s\S]*?)\*\//g, '<span class="text-slate-400 italic">/**$1*/</span>')
          }} />
        </pre>
      </div>
    </div>
  )
}

