"use client"

import * as React from "react"
import { useBuilderStore } from "@/store/useBuilderStore"
import { Copy, Check, Terminal, Download, FileCode, Play, Sparkles } from "lucide-react"
import { QuantScratchpad } from "@/components/builder/QuantScratchpad"
import { toast } from "sonner"

export type CodeViewTab = 'python' | 'pinescript' | 'nodejs' | 'json' | 'scratchpad';

export function CodeViewer() {
  const { strategyDSL, strategyName } = useBuilderStore()
  const [copied, setCopied] = React.useState(false)
  const [tab, setTab] = React.useState<CodeViewTab>('python')

  const formatPythonIndicator = (ind: any) => {
    if (!ind || ind.type === 'PRICE') return `df['close']`;
    if (ind.type === 'OPEN') return `df['open']`;
    if (ind.type === 'HIGH') return `df['high']`;
    if (ind.type === 'LOW') return `df['low']`;
    if (ind.type === 'VOLUME') return `df['volume']`;
    const period = ind.parameters?.period || ind.parameters?.fast || 14;
    if (ind.type === 'EMA') return `ta.ema(df['close'], length=${period})`;
    if (ind.type === 'SMA') return `ta.sma(df['close'], length=${period})`;
    if (ind.type === 'WMA') return `ta.wma(df['close'], length=${period})`;
    if (ind.type === 'HMA') return `ta.hma(df['close'], length=${period})`;
    if (ind.type === 'RSI') return `ta.rsi(df['close'], length=${period})`;
    if (ind.type === 'ATR') return `ta.atr(df['high'], df['low'], df['close'], length=${period})`;
    if (ind.type === 'BOLLINGER_LOWER') return `ta.bbands(df['close'], length=${period})['BBL_${period}_2.0']`;
    if (ind.type === 'BOLLINGER_UPPER') return `ta.bbands(df['close'], length=${period})['BBU_${period}_2.0']`;
    if (ind.type === 'BOLLINGER_MIDDLE') return `ta.sma(df['close'], length=${period})`;
    if (ind.type === 'MACD') return `ta.macd(df['close'])['MACD_12_26_9']`;
    if (ind.type === 'MACD_SIGNAL') return `ta.macd(df['close'])['MACDs_12_26_9']`;
    if (ind.type === 'MACD_HISTOGRAM') return `ta.macd(df['close'])['MACDh_12_26_9']`;
    if (ind.type === 'SUPERTREND') return `ta.supertrend(df['high'], df['low'], df['close'])['SUPERT_7_3.0']`;
    if (ind.type === 'STOCHASTIC_K') return `ta.stoch(df['high'], df['low'], df['close'])['STOCHk_14_3_3']`;
    if (ind.type === 'STOCHASTIC_D') return `ta.stoch(df['high'], df['low'], df['close'])['STOCHd_14_3_3']`;
    if (ind.type === 'ADX') return `ta.adx(df['high'], df['low'], df['close'])['ADX_14']`;
    if (ind.type === 'CCI') return `ta.cci(df['high'], df['low'], df['close'], length=${period})`;
    if (ind.type === 'OBV') return `ta.obv(df['close'], df['volume'])`;
    if (ind.type === 'WILLIAMS_R') return `ta.willr(df['high'], df['low'], df['close'], length=${period})`;
    if (ind.type === 'VWAP') return `ta.vwap(df['high'], df['low'], df['close'], df['volume'])`;
    if (ind.type === 'VOLUME_SMA') return `ta.sma(df['volume'], length=${period})`;
    return `df['close']`;
  };

  const formatPythonCondition = (cond: any) => {
    const left = formatPythonIndicator(cond.left);
    const right = typeof cond.right === 'object' && cond.right !== null ? formatPythonIndicator(cond.right) : cond.right;
    const compMap: Record<string, string> = {
      GREATER_THAN: '>',
      LESS_THAN: '<',
      EQUAL: '==',
      GREATER_THAN_OR_EQUAL: '>=',
      LESS_THAN_OR_EQUAL: '<=',
      CROSSES_ABOVE: '>',
      CROSSES_BELOW: '<'
    };
    return `${left}.iloc[-1] ${compMap[cond.comparator] || '>'} ${right}`;
  };

  const generatePythonCode = () => {
    if (!strategyDSL) {
      return `# No strategy configured yet.\n# Use AI Copilot or Block Library to build your quant algorithm.\n`;
    }

    const { name, instruments, entryConditions, exitConditions, action, riskParameters } = strategyDSL;
    const symbol = instruments?.[0]?.symbol || 'BTC/USDT';
    const stopLoss = riskParameters?.stopLossPercentage || 3.0;
    const takeProfit = riskParameters?.takeProfitPercentage || 6.0;
    const actionType = action?.type || 'BUY';
    const quantityVal = action?.quantityValue || 50;

    const entryCodeStr = entryConditions?.length > 0
      ? entryConditions.map(formatPythonCondition).join(" and ")
      : "True";

    const exitCodeStr = exitConditions && exitConditions.length > 0
      ? exitConditions.map(formatPythonCondition).join(" or ")
      : "False";

    return `"""
Strategy: ${name}
Generated by AlgoText Quantitative AI Engine
Stack: Python 3.10+, CCXT, pandas_ta, Binance / LBank / OKX / 60+ Exchange REST & WebSockets
"""
import ccxt
import pandas as pd
import pandas_ta as ta
import numpy as np
import time
import os

API_KEY = os.getenv("EXCHANGE_API_KEY", "YOUR_EXCHANGE_API_KEY")
SECRET_KEY = os.getenv("EXCHANGE_SECRET_KEY", "YOUR_EXCHANGE_SECRET")

# Initialize CCXT exchange client
exchange = ccxt.binance({
    'apiKey': API_KEY,
    'secret': SECRET_KEY,
    'enableRateLimit': True,
    'options': {'defaultType': 'future'}
})

SYMBOL = "${symbol}"

def calculate_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """Calculates quantitative technical indicators using pandas_ta."""
    df = df.copy()
    df['EMA_50'] = ta.ema(df['close'], length=50)
    df['EMA_200'] = ta.ema(df['close'], length=200)
    df['RSI_14'] = ta.rsi(df['close'], length=14)
    df['ATRr_14'] = ta.atr(df['high'], df['low'], df['close'], length=14)
    return df

def generate_signals(df: pd.DataFrame):
    """Evaluates multi-condition strategy logic on latest candle."""
    entry_signal = ${entryCodeStr}
    exit_signal = ${exitCodeStr}
    return entry_signal, exit_signal

def execute_orders(action_type: str, qty_percent: float):
    """Submits order to Exchange API with bracket SL/TP."""
    balance = exchange.fetch_balance()
    usdt_free = balance['USDT']['free']
    ticker = exchange.fetch_ticker(SYMBOL)
    price = ticker['last']
    
    amount = (usdt_free * (qty_percent / 100)) / price
    
    print(f"[EXCHANGE WORKER] Submitting {action_type} order for {amount:.4f} {SYMBOL} at \${price}")
    if action_type == 'BUY':
        order = exchange.create_market_buy_order(SYMBOL, amount)
        sl_price = price * (1 - (${stopLoss} / 100))
        tp_price = price * (1 + (${takeProfit} / 100))
        exchange.create_order(SYMBOL, 'STOP_MARKET', 'sell', amount, None, {'stopPrice': sl_price})
        exchange.create_order(SYMBOL, 'TAKE_PROFIT_MARKET', 'sell', amount, None, {'stopPrice': tp_price})
        return order
    elif action_type == 'SELL':
        order = exchange.create_market_sell_order(SYMBOL, amount)
        sl_price = price * (1 + (${stopLoss} / 100))
        tp_price = price * (1 - (${takeProfit} / 100))
        exchange.create_order(SYMBOL, 'STOP_MARKET', 'buy', amount, None, {'stopPrice': sl_price})
        exchange.create_order(SYMBOL, 'TAKE_PROFIT_MARKET', 'buy', amount, None, {'stopPrice': tp_price})
        return order
    elif action_type == 'CLOSE_POSITION':
        return exchange.create_market_sell_order(SYMBOL, amount)

def run():
    print(f"Starting AlgoText Automated Quantitative Bot for {SYMBOL}...")
    while True:
        try:
            ohlcv = exchange.fetch_ohlcv(SYMBOL, timeframe='5m', limit=150)
            df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
            df = calculate_indicators(df)
            entry, exit_sig = generate_signals(df)
            
            positions = exchange.fetch_positions([SYMBOL])
            has_position = len(positions) > 0 and float(positions[0]['contracts']) > 0
            
            if entry and not has_position:
                execute_orders('${actionType}', ${quantityVal})
            elif exit_sig and has_position:
                execute_orders('CLOSE_POSITION', 100)
                
        except Exception as e:
            print(f"[ERROR] Strategy execution exception: {e}")
            
        time.sleep(15)

if __name__ == "__main__":
    run()
`;
  }

  const formatPineIndicator = (ind: any) => {
    if (!ind || ind.type === 'PRICE') return `close`;
    if (ind.type === 'OPEN') return `open`;
    if (ind.type === 'HIGH') return `high`;
    if (ind.type === 'LOW') return `low`;
    if (ind.type === 'VOLUME') return `volume`;
    const period = ind.parameters?.period || ind.parameters?.fast || 14;
    if (ind.type === 'EMA') return `ta.ema(close, ${period})`;
    if (ind.type === 'SMA') return `ta.sma(close, ${period})`;
    if (ind.type === 'WMA') return `ta.wma(close, ${period})`;
    if (ind.type === 'HMA') return `ta.hma(close, ${period})`;
    if (ind.type === 'RSI') return `ta.rsi(close, ${period})`;
    if (ind.type === 'ATR') return `ta.atr(${period})`;
    if (ind.type === 'BOLLINGER_LOWER') return `ta.bbands(close, ${period}, 2.0)[2]`;
    if (ind.type === 'BOLLINGER_UPPER') return `ta.bbands(close, ${period}, 2.0)[0]`;
    if (ind.type === 'BOLLINGER_MIDDLE') return `ta.sma(close, ${period})`;
    if (ind.type === 'MACD') return `ta.macd(close, 12, 26, 9)[0]`;
    if (ind.type === 'MACD_SIGNAL') return `ta.macd(close, 12, 26, 9)[1]`;
    if (ind.type === 'MACD_HISTOGRAM') return `ta.macd(close, 12, 26, 9)[2]`;
    if (ind.type === 'SUPERTREND') return `ta.supertrend(3.0, 10)[0]`;
    if (ind.type === 'STOCHASTIC_K') return `ta.stoch(close, high, low, 14)`;
    if (ind.type === 'STOCHASTIC_D') return `ta.sma(ta.stoch(close, high, low, 14), 3)`;
    if (ind.type === 'ADX') return `ta.adx(14)`;
    if (ind.type === 'CCI') return `ta.cci(close, ${period})`;
    if (ind.type === 'OBV') return `ta.obv`;
    if (ind.type === 'WILLIAMS_R') return `ta.wpr(${period})`;
    if (ind.type === 'VWAP') return `ta.vwap`;
    if (ind.type === 'VOLUME_SMA') return `ta.sma(volume, ${period})`;
    return `close`;
  };

  const formatPineCondition = (cond: any) => {
    const left = formatPineIndicator(cond.left);
    const right = typeof cond.right === 'object' && cond.right !== null ? formatPineIndicator(cond.right) : cond.right;
    if (cond.comparator === 'CROSSES_ABOVE') return `ta.crossover(${left}, ${right})`;
    if (cond.comparator === 'CROSSES_BELOW') return `ta.crossunder(${left}, ${right})`;
    const compMap: Record<string, string> = {
      GREATER_THAN: '>',
      LESS_THAN: '<',
      EQUAL: '==',
      GREATER_THAN_OR_EQUAL: '>=',
      LESS_THAN_OR_EQUAL: '<='
    };
    return `${left} ${compMap[cond.comparator] || '>'} ${right}`;
  };

  const generatePineScriptCode = () => {
    if (!strategyDSL) return `//@version=5\n// No strategy configured yet.`;
    const { name, entryConditions, exitConditions, action, riskParameters } = strategyDSL;
    const isShort = action?.type === 'SELL';
    
    let code = `//@version=5\nstrategy("${name}", overlay=true, initial_capital=10000, default_qty_type=strategy.percent_of_equity, default_qty_value=50)\n\n`;
    code += `// --- ENTRY CONDITIONS ---\n`;
    const entryStr = entryConditions?.length > 0 ? entryConditions.map(formatPineCondition).join(" and ") : "true";
    code += `entryCondition = ${entryStr}\n\n`;
    
    code += `// --- EXIT CONDITIONS ---\n`;
    const exitStr = exitConditions && exitConditions.length > 0 ? exitConditions.map(formatPineCondition).join(" or ") : "false";
    code += `exitCondition = ${exitStr}\n\n`;
    
    if (!isShort) {
      code += `if (entryCondition)\n    strategy.entry("Long Entry", strategy.long)\n\n`;
      code += `if (exitCondition)\n    strategy.close("Long Entry")\n\n`;
    } else {
      code += `if (entryCondition)\n    strategy.entry("Short Entry", strategy.short)\n\n`;
      code += `if (exitCondition)\n    strategy.close("Short Entry")\n\n`;
    }

    if (riskParameters) {
      const sl = (riskParameters.stopLossPercentage || 3) / 100;
      const tp = (riskParameters.takeProfitPercentage || 6) / 100;
      const posName = !isShort ? "Long Entry" : "Short Entry";
      const slPrice = !isShort ? `strategy.position_avg_price * (1 - ${sl})` : `strategy.position_avg_price * (1 + ${sl})`;
      const tpPrice = !isShort ? `strategy.position_avg_price * (1 + ${tp})` : `strategy.position_avg_price * (1 - ${tp})`;
      code += `// --- RISK BRACKET (SL/TP) ---\n`;
      code += `strategy.exit("Bracket", "${posName}", stop=${slPrice}, limit=${tpPrice})\n`;
    }
    return code;
  }

  const generateNodeJSCode = () => {
    if (!strategyDSL) return `// No strategy configured yet.`;
    const { name, instruments } = strategyDSL;
    const symbol = instruments?.[0]?.symbol || 'BTC/USDT';
    
    return `/**
 * Strategy: ${name}
 * Auto-generated CCXT Node.js Trading Engine (Binance / LBank / OKX / 60+ exchanges)
 */
const ccxt = require('ccxt');

const exchange = new ccxt.binance({
  apiKey: process.env.EXCHANGE_API_KEY,
  secret: process.env.EXCHANGE_SECRET_KEY,
  enableRateLimit: true,
  options: { defaultType: 'future' }
});

const SYMBOL = '${symbol}';

async function run() {
  console.log("Starting Quantitative Worker for " + SYMBOL);
  setInterval(async () => {
    try {
      const ohlcv = await exchange.fetchOHLCV(SYMBOL, '1m', undefined, 100);
      const closes = ohlcv.map(c => c[4]);
      const latestClose = closes[closes.length - 1];
      console.log(\`[TICK] \${SYMBOL} Price: \${latestClose}\`);
    } catch (e) {
      console.error("[ERROR] ", e.message);
    }
  }, 10000);
}

run();`;
  }

  const getCode = () => {
    if (tab === 'python') return generatePythonCode();
    if (tab === 'pinescript') return generatePineScriptCode();
    if (tab === 'nodejs') return generateNodeJSCode();
    if (tab === 'json') return JSON.stringify(strategyDSL, null, 2);
    return "";
  }

  const code = getCode();

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    toast.success("Code copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  }

  const handleDownload = () => {
    if (tab === 'scratchpad') return;
    const extMap: Record<string, string> = { python: "py", pinescript: "pine", nodejs: "js", json: "json" };
    const filename = `${strategyName.toLowerCase().replace(/[^a-z0-9]/g, '_')}.${extMap[tab] || 'txt'}`;
    const blob = new Blob([code], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${filename}`);
  }

  if (tab === 'scratchpad') {
    return (
      <div className="flex flex-1 flex-col border-t border-bg-border bg-bg-surface overflow-hidden h-full">
        <div className="flex h-[36px] shrink-0 items-center justify-between border-b border-bg-border bg-bg-base px-3">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setTab('python')}
              className="text-[11.5px] text-text-secondary hover:text-text-primary px-2 py-0.5 rounded"
            >
              ← Back to Code Viewer
            </button>
            <div className="h-3 w-px bg-bg-border" />
            <span className="text-[11.5px] font-bold text-accent-green flex items-center gap-1">
              <Sparkles className="h-3.5 w-3.5" /> Scratchpad & Localhost:3000 Engine Active
            </span>
          </div>

          <div className="flex rounded-md bg-bg-elevated p-0.5 border border-bg-border">
            <button
              onClick={() => setTab("python")}
              className="px-2 py-0.5 text-[11px] font-semibold text-text-secondary rounded"
            >
              Python
            </button>
            <button
              onClick={() => setTab("pinescript")}
              className="px-2 py-0.5 text-[11px] font-semibold text-text-secondary rounded"
            >
              PineScript
            </button>
            <button
              onClick={() => setTab("nodejs")}
              className="px-2 py-0.5 text-[11px] font-semibold text-text-secondary rounded"
            >
              Node.js
            </button>
            <button
              onClick={() => setTab("scratchpad")}
              className="px-2 py-0.5 text-[11px] font-bold bg-accent-blue text-white rounded"
            >
              Scratchpad (Backtest)
            </button>
          </div>
        </div>
        <div className="flex-1 overflow-hidden">
          <QuantScratchpad />
        </div>
      </div>
    )
  }

  return (
    <div className="flex flex-1 flex-col border-t border-bg-border bg-bg-surface overflow-hidden shadow-sm h-full">
      <div className="flex h-[40px] shrink-0 items-center justify-between border-b border-bg-border bg-bg-base px-4">
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1.5 text-[12px] font-bold text-text-primary">
            <Terminal className="h-4 w-4 text-accent-blue" />
            <span>Code Export & Simulator</span>
          </div>

          <div className="h-4 w-px bg-bg-border" />

          <div className="flex rounded-lg bg-bg-elevated p-0.5 border border-bg-border">
            <button
              onClick={() => setTab("python")}
              className={`px-2.5 py-1 text-[11px] font-semibold rounded-md transition-colors ${tab === "python" ? "bg-accent-blue text-white" : "text-text-secondary hover:text-text-primary"}`}
            >
              main.py (Python)
            </button>
            <button
              onClick={() => setTab("pinescript")}
              className={`px-2.5 py-1 text-[11px] font-semibold rounded-md transition-colors ${tab === "pinescript" ? "bg-accent-blue text-white" : "text-text-secondary hover:text-text-primary"}`}
            >
              strategy.pine (TradingView)
            </button>
            <button
              onClick={() => setTab("nodejs")}
              className={`px-2.5 py-1 text-[11px] font-semibold rounded-md transition-colors ${tab === "nodejs" ? "bg-accent-blue text-white" : "text-text-secondary hover:text-text-primary"}`}
            >
              index.js (Node.js)
            </button>
            <button
              onClick={() => setTab("json")}
              className={`px-2.5 py-1 text-[11px] font-semibold rounded-md transition-colors ${tab === "json" ? "bg-accent-blue text-white" : "text-text-secondary hover:text-text-primary"}`}
            >
              strategy_dsl.json
            </button>
            <button
              onClick={() => setTab("scratchpad")}
              className="px-2.5 py-1 text-[11px] font-bold rounded-md bg-accent-green/20 text-accent-green border border-accent-green/30 hover:bg-accent-green hover:text-white transition-all flex items-center gap-1 ml-1"
            >
              <Play className="h-3 w-3 fill-current" />
              Quant Scratchpad & Backtest
            </button>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button 
            onClick={handleDownload}
            className="flex items-center gap-1.5 rounded-lg px-2.5 py-1 text-[12px] text-text-secondary hover:bg-bg-elevated hover:text-text-primary transition-colors"
          >
            <Download className="h-3.5 w-3.5" />
            <span>Download .{tab === 'python' ? 'py' : tab === 'pinescript' ? 'pine' : tab === 'nodejs' ? 'js' : 'json'}</span>
          </button>

          <button 
            onClick={handleCopy}
            className="flex items-center gap-1.5 rounded-lg px-2.5 py-1 text-[12px] text-text-secondary hover:bg-bg-elevated hover:text-text-primary transition-colors"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-accent-green" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Code'}</span>
          </button>
        </div>
      </div>
      <div className="flex-1 overflow-auto p-4 bg-bg-base border-t border-bg-border">
        <pre className="font-mono text-[12.5px] text-text-primary leading-relaxed">
          <code>{code}</code>
        </pre>
      </div>
    </div>
  )
}
