"use client"

import * as React from "react"
import { 
  Download, Upload, Copy, Check, FileCode, FileText, Code2, 
  X, Sparkles, CheckCircle2, Terminal
} from "lucide-react"
import { useBuilderStore } from "@/store/useBuilderStore"
import { toast } from "sonner"

export function StrategyImportExportModal({
  isOpen,
  onClose
}: {
  isOpen: boolean
  onClose: () => void
}) {
  const { 
    strategyDSL, 
    strategyName, 
    nodes, 
    edges, 
    tradingPair, 
    timeframe,
    setNodes,
    setEdges,
    setStrategyName,
    setTradingPair,
    setTimeframe,
    updateStrategy,
    compileGraphToDSL
  } = useBuilderStore()

  const [activeTab, setActiveTab] = React.useState<'export' | 'import'>('export')
  const [exportFormat, setExportFormat] = React.useState<'json' | 'python' | 'pinescript' | 'yaml'>('json')
  const [importText, setImportText] = React.useState('')
  const [copied, setCopied] = React.useState(false)

  // Generate Export Code based on format
  const exportedCode = React.useMemo(() => {
    if (exportFormat === 'json') {
      const exportObject = {
        metadata: {
          generator: "AlgoRush Institutional Quant Engine",
          version: "2.0.0",
          timestamp: new Date().toISOString(),
          strategyName,
          pair: tradingPair,
          timeframe
        },
        dsl: strategyDSL,
        canvas: {
          nodes,
          edges
        }
      }
      return JSON.stringify(exportObject, null, 2)
    } else if (exportFormat === 'yaml') {
      return `version: "2.0"
strategy:
  name: "${strategyName}"
  instrument: "${tradingPair}"
  timeframe: "${timeframe}"
  action:
    type: "${strategyDSL?.action?.type || 'BUY'}"
    leverage: ${strategyDSL?.action?.leverage || 1}x
    allocation: ${strategyDSL?.action?.quantityValue || 50}%
  risk:
    stop_loss_pct: ${strategyDSL?.riskParameters?.stopLossPercentage || 3.0}
    take_profit_pct: ${strategyDSL?.riskParameters?.takeProfitPercentage || 6.0}
    trailing_stop_pct: ${strategyDSL?.riskParameters?.trailingStopPercentage || 1.5}
  nodes_count: ${nodes.length}
  edges_count: ${edges.length}
`
    } else if (exportFormat === 'python') {
      return `"""
Autonomous Quantitative Strategy: ${strategyName}
Generated by AlgoRush AI Quant Suite
"""
import ccxt
import pandas as pd
import pandas_ta as ta
import time
import os

EXCHANGE = ccxt.binance({
    'apiKey': os.getenv('BINANCE_API_KEY'),
    'secret': os.getenv('BINANCE_SECRET'),
    'enableRateLimit': True,
    'options': {'defaultType': 'future'}
})

SYMBOL = "${tradingPair}"
TIMEFRAME = "${timeframe}"

def run_loop():
    print(f"Deploying {SYMBOL} Strategy...")
    while True:
        try:
            bars = EXCHANGE.fetch_ohlcv(SYMBOL, TIMEFRAME, limit=100)
            df = pd.DataFrame(bars, columns=['time', 'open', 'high', 'low', 'close', 'vol'])
            # Logic evaluation
            print(f"[HEARTBEAT] {SYMBOL} latest close: {df['close'].iloc[-1]}")
        except Exception as err:
            print("Execution error:", err)
        time.sleep(10)

if __name__ == '__main__':
    run_loop()
`
    } else if (exportFormat === 'pinescript') {
      return `//@version=5
strategy("${strategyName}", overlay=true, initial_capital=10000, default_qty_type=strategy.percent_of_equity, default_qty_value=50)

// Parameters
sl_pct = ${strategyDSL?.riskParameters?.stopLossPercentage || 3.0} / 100
tp_pct = ${strategyDSL?.riskParameters?.takeProfitPercentage || 6.0} / 100

// Signals
longCondition = ta.crossover(ta.ema(close, 50), ta.ema(close, 200))
if (longCondition)
    strategy.entry("Long Entry", strategy.long)

strategy.exit("Bracket", "Long Entry", stop=strategy.position_avg_price * (1 - sl_pct), limit=strategy.position_avg_price * (1 + tp_pct))
`
    }
    return ""
  }, [exportFormat, strategyDSL, strategyName, nodes, edges, tradingPair, timeframe])

  const handleCopy = () => {
    navigator.clipboard.writeText(exportedCode)
    setCopied(true)
    toast.success("Strategy exported to clipboard!")
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const ext = exportFormat === 'json' ? 'json' : exportFormat === 'python' ? 'py' : exportFormat === 'pinescript' ? 'pine' : 'yaml'
    const blob = new Blob([exportedCode], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${strategyName.toLowerCase().replace(/\s+/g, '_')}_strategy.${ext}`
    link.click()
    URL.revokeObjectURL(url)
    toast.success(`Downloaded ${link.download}`)
  }

  const handleImport = () => {
    if (!importText.trim()) {
      toast.error("Please paste valid strategy JSON to import.")
      return
    }

    try {
      const parsed = JSON.parse(importText)
      if (parsed.canvas?.nodes && Array.isArray(parsed.canvas.nodes)) {
        setNodes(parsed.canvas.nodes)
        setEdges(parsed.canvas.edges || [])
        if (parsed.metadata?.strategyName) setStrategyName(parsed.metadata.strategyName)
        if (parsed.metadata?.pair) setTradingPair(parsed.metadata.pair)
        if (parsed.metadata?.timeframe) setTimeframe(parsed.metadata.timeframe)
        if (parsed.dsl) updateStrategy(parsed.dsl)
        toast.success("✨ Strategy DAG & DSL successfully imported to canvas!")
        onClose()
      } else if (parsed.entryConditions || parsed.action) {
        // Direct DSL object import
        updateStrategy(parsed)
        if (parsed.name) setStrategyName(parsed.name)
        compileGraphToDSL()
        toast.success("✨ Strategy DSL imported and compiled!")
        onClose()
      } else {
        toast.error("Unrecognized strategy schema format.")
      }
    } catch (err: any) {
      toast.error("Failed to parse JSON: " + (err?.message || "Invalid syntax"))
    }
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 backdrop-blur-md p-4 animate-in fade-in duration-200">
      <div className="relative flex max-h-[90vh] w-full max-w-2xl flex-col rounded-2xl border border-bg-border bg-bg-surface shadow-2xl overflow-hidden">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-bg-border px-6 py-4 bg-bg-elevated/40 shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-accent-blue/15 border border-accent-blue/30 text-accent-blue">
              {activeTab === 'export' ? <Download className="h-5 w-5" /> : <Upload className="h-5 w-5" />}
            </div>
            <div>
              <h2 className="text-[16px] font-bold text-text-primary">
                Strategy Portability Hub
              </h2>
              <p className="text-[11.5px] text-text-secondary">
                Export to production stacks or import existing algorithm configurations
              </p>
            </div>
          </div>
          
          <button 
            onClick={onClose}
            className="p-1 rounded-lg text-text-secondary hover:text-text-primary hover:bg-bg-elevated transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Tab Switcher */}
        <div className="flex items-center justify-between px-6 pt-4 shrink-0">
          <div className="flex rounded-xl bg-bg-elevated p-1 border border-bg-border">
            <button
              onClick={() => setActiveTab('export')}
              className={`flex items-center gap-1.5 px-3 py-1 text-[11.5px] font-bold rounded-lg transition-all ${
                activeTab === 'export' ? 'bg-accent-blue text-white shadow-sm' : 'text-text-secondary hover:text-text-primary'
              }`}
            >
              <Download className="h-3.5 w-3.5" />
              <span>Export Strategy</span>
            </button>
            <button
              onClick={() => setActiveTab('import')}
              className={`flex items-center gap-1.5 px-3 py-1 text-[11.5px] font-bold rounded-lg transition-all ${
                activeTab === 'import' ? 'bg-accent-blue text-white shadow-sm' : 'text-text-secondary hover:text-text-primary'
              }`}
            >
              <Upload className="h-3.5 w-3.5" />
              <span>Import Strategy</span>
            </button>
          </div>

          {activeTab === 'export' && (
            <div className="flex items-center gap-1 rounded-xl bg-bg-elevated p-1 border border-bg-border text-[11px] font-bold">
              {(['json', 'python', 'pinescript', 'yaml'] as const).map((fmt) => (
                <button
                  key={fmt}
                  onClick={() => setExportFormat(fmt)}
                  className={`px-2.5 py-0.5 rounded-lg uppercase transition-all ${
                    exportFormat === fmt ? 'bg-bg-surface text-accent-blue shadow-xs' : 'text-text-secondary hover:text-text-primary'
                  }`}
                >
                  {fmt}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-6">
          {activeTab === 'export' && (
            <div className="flex flex-col gap-3">
              <div className="flex items-center justify-between text-[11.5px]">
                <span className="font-mono text-text-tertiary">
                  Target: {exportFormat.toUpperCase()} ({exportedCode.split('\n').length} lines)
                </span>
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopy}
                    className="flex items-center gap-1 px-2.5 py-1 rounded-lg border border-bg-border bg-bg-base hover:bg-bg-elevated text-text-secondary text-[11px] font-bold transition-all"
                  >
                    {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
                    <span>{copied ? 'Copied' : 'Copy'}</span>
                  </button>
                  <button
                    onClick={handleDownload}
                    className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-accent-blue hover:bg-blue-600 text-white text-[11px] font-bold shadow-xs transition-all"
                  >
                    <Download className="h-3.5 w-3.5" />
                    <span>Download File</span>
                  </button>
                </div>
              </div>

              <pre className="max-h-[380px] overflow-auto rounded-xl border border-bg-border bg-bg-base p-3.5 font-mono text-[11px] text-text-secondary leading-relaxed scrollbar-thin">
                <code>{exportedCode}</code>
              </pre>
            </div>
          )}

          {activeTab === 'import' && (
            <div className="flex flex-col gap-3">
              <p className="text-[12px] text-text-secondary leading-relaxed">
                Paste an AlgoRush Strategy JSON or DSL specification below to restore the complete visual flowchart DAG, node properties, and execution rules.
              </p>

              <textarea
                value={importText}
                onChange={(e) => setImportText(e.target.value)}
                placeholder='Paste strategy JSON object here... e.g. { "metadata": { ... }, "canvas": { "nodes": [...] } }'
                className="h-[280px] w-full rounded-xl border border-bg-border bg-bg-base p-3 font-mono text-[11.5px] text-text-primary outline-none focus:border-accent-blue focus:shadow-[0_0_0_2px_rgba(59,130,246,0.15)] transition-all resize-none"
              />

              <button
                onClick={handleImport}
                className="flex items-center justify-center gap-2 w-full py-2.5 rounded-xl bg-accent-blue hover:bg-blue-600 text-white text-[12.5px] font-bold shadow-md shadow-accent-blue/20 transition-all"
              >
                <Upload className="h-4 w-4" />
                <span>Load Strategy Onto Canvas</span>
              </button>
            </div>
          )}
        </div>

      </div>
    </div>
  )
}
