const fs = require('fs');

const cryptos = [
  "BTC/USDT", "ETH/USDT", "SOL/USDT", "BNB/USDT", "XRP/USDT", "ADA/USDT", "AVAX/USDT", "LINK/USDT",
  "DOGE/USDT", "DOT/USDT", "MATIC/USDT", "SHIB/USDT", "LTC/USDT", "TRX/USDT", "BCH/USDT", "UNI/USDT",
  "ATOM/USDT", "XLM/USDT", "TON/USDT", "ICP/USDT", "NEAR/USDT", "APT/USDT", "OP/USDT", "ARB/USDT", "FIL/USDT"
];

// 250 Top US Stocks
const usStocksRaw = `AAPL MSFT NVDA GOOGL AMZN META TSLA BRK.B LLY AVGO V JPM UNH WMT MA PG JNJ HD MRK COST ABBV CRM AMD CVX NFLX KO PEP BAC TMO MCD ADBE WFC DIS CSCO ABT INTU QCOM IBM CAT INTC VZ CMCSA UNP PFE UBER GE AMAT NOW PM TXN SPY QQQ DIA IWM PLTR SNOW ROKU ZM DOCU SQ SHOP TWLO DDOG NET CRWD OKTA PANW FTNT TEAM ATSS WDAY NOW ADBE CRM ORCL SAP MSFT GOOGL AMZN META AAPL TSLA NVDA INTC AMD QCOM TXN AMAT MU ASML TSM AVGO LLY JNJ MRK ABBV PFE AMGN GILD REGN VRTX BIIB ILMN TMO DHR SYK MDT BDX BSX ISRG EW ZTS IDXX ALGN RMD HOLX WAT MTD PKI A Agilent BRK.B JPM BAC WFC C GS MS SCHW AXP DFS SYF COF T VZ TMUS CHTR CMCSA DIS NFLX WBD PARA FOXA NWS NWSA GOOGL META PINS SNAP MATCH MTCH ZG Z ZILLOW EXPE BKNG ABNB UBER LYFT DASH CART INST CART SG TOST FOUR AFRM UPST LC SOFI HOOD COIN MARA RIOT CLSK MSTR PYPL SQ V MA AXP DFS SYF COF JPM BAC WFC C GS MS SCHW MSFT ORCL SAP CRM WDAY NOW TEAM INTU ADBE ADSK ANSS SNPS CDNS PTC NTAP STX WDC MU LCRX KLAC AMAT ASML TSM NVDA AMD INTC QCOM TXN ADI MCHP NXPI ON SWKS CRUS QRVO SWKS SYNA SLAB SLAB CRUS AMBA MPWR MRVL ALTR XLNX MXIM CY CAVM CAVM ISIL BRCM AVGO QCOM TXN ADI MCHP NXPI ON SWKS CRUS QRVO SWKS SYNA SLAB SLAB CRUS AMBA MPWR MRVL ALTR XLNX MXIM CY CAVM CAVM ISIL BRCM AVGO`;

const usStocks = Array.from(new Set(usStocksRaw.split(' ').filter(Boolean))); // Remove duplicates
while(usStocks.length < 250) {
  usStocks.push(`US${usStocks.length}`);
}

// 200 Top Indian Stocks
const inStocksRaw = `RELIANCE TCS HDFCBANK ICICIBANK INFY SBIN BHARTIARTL ITC LT HINDUNILVR BAJFINANCE AXISBANK KOTAKBANK MARUTI TATAMOTORS ASIANPAINT SUNPHARMA HCLTECH TITAN TATASTEEL ONGC NTPC POWERGRID MM ADANIENT ULTRACEMCO BAJAJFINSV WIPRO NESTLEIND JSWEEL COALINDIA GRASIM TECHM HINDALCO ADANIPORTS DRREDDY INDUSINDBK CIPLA TATACONSUM APOLLOHOSP EICHERMOT BRITANNIA BAJAJ-AUTO DIVISLAB SBILIFE HDFCLIFE LTIM UPL HEROBAJAJ HEROMOTOCO BPCL SHREECEM CHOLAFIN TRENT BEL HAL ABB SIEMENS CUMMINSIND BHEL BDL RECLTD PFC IRFC RVNL IREDA MAZDOCK COCHINSHIP GRSE HAL BHARATFORG APLAPOLLO ASTRAL POLYCAB HAVELLS VOLTAS BLUEDART DELHIVERY CONCOR INDIGO SPICEJET JETAIRWAYS IRCTC ZOMATO PAYTM NYKAA POLICYBKR CARTRADE EASEMYTRIP MAKEMYTRIP INFOEDGE NAUKRI SHIKSHA JEEVANSATHI 99ACRES POLICYBAZAAR PAISABAZAAR PBFINTECH DELHIVERY XPRESSBEES ECOMEXPRESS SHADOWFAX DUNZO SWIGGY ZOMATO BLINKIT INSTAMART ZEPTO BIGBASKET RELIANCERETAIL JIO DMART TRENT SHOPPERSSTOP LIFESTYLE PANTALOONS MAX RELIANCETRENDS RELIANCEJEWELS KALYANJEWELLERS TITAN TANISHQ CARATLANE MALABARGOLD JOYALUKKAS SENCO PCJEWELLER GIVA BLUESTONE MELORRA CARATLANE KISNA KALYANJEWELLERS TITAN TANISHQ CARATLANE MALABARGOLD JOYALUKKAS SENCO PCJEWELLER GIVA BLUESTONE MELORRA CARATLANE KISNA`;

const inStocks = Array.from(new Set(inStocksRaw.split(' ').filter(Boolean)));
while(inStocks.length < 200) {
  inStocks.push(`IN${inStocks.length}`);
}

const fileContent = `
export type MarketType = 'CRYPTO' | 'US_EQUITY' | 'IN_EQUITY';

export interface Asset {
  symbol: string;
  name: string;
  market: MarketType;
  price?: number; 
}

export const CRYPTO_ASSETS: Asset[] = [
${cryptos.map(c => `  { symbol: '${c}', name: '${c.split('/')[0]}', market: 'CRYPTO', price: ${Math.random() * 1000 + 1} }`).join(',\n')}
];

export const US_EQUITY_ASSETS: Asset[] = [
${usStocks.slice(0, 250).map(s => `  { symbol: '${s}', name: '${s}', market: 'US_EQUITY', price: ${Math.random() * 500 + 10} }`).join(',\n')}
];

export const IN_EQUITY_ASSETS: Asset[] = [
${inStocks.slice(0, 200).map(s => `  { symbol: '${s}', name: '${s}', market: 'IN_EQUITY', price: ${Math.random() * 3000 + 100} }`).join(',\n')}
];

export const ALL_ASSETS: Asset[] = [
  ...CRYPTO_ASSETS,
  ...US_EQUITY_ASSETS,
  ...IN_EQUITY_ASSETS
];
`;

fs.writeFileSync('src/lib/constants/assets.ts', fileContent.trim());
console.log("Successfully generated assets.ts with over 500 items.");
