"use client"

import * as React from "react"
import { motion } from "framer-motion"
import { Users, DollarSign, Activity, ArrowRight, Link as LinkIcon, Gift } from "lucide-react"
import { BackButton } from "@/components/ui/BackButton"

export default function AffiliatesPage() {
  const [referrals, setReferrals] = React.useState(50)
  
  // Simulated dynamic calculation
  const monthlyEarnings = referrals * 45 // Assuming average $45/mo generated per user

  return (
    <div className="min-h-screen bg-bg-primary pt-24 pb-32">
      {/* Hero */}
      <section className="mx-auto max-w-[1000px] px-6 py-20 text-center">
        <div className="flex justify-start"><BackButton /></div>
        <motion.div 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
          className="mb-6 inline-flex items-center gap-2 rounded-full border border-accent-green/30 bg-accent-green/10 px-4 py-1.5 text-sm font-semibold text-accent-green"
        >
          <Gift className="h-4 w-4" /> Partner Program Now Live
        </motion.div>
        <motion.h1 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
          className="mb-8 text-5xl font-bold text-text-primary md:text-7xl tracking-tight"
        >
          Earn <span className="text-accent-green">30%</span> of every trade. <br/> For life.
        </motion.h1>
        <motion.p 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
          className="mx-auto mb-10 max-w-[600px] text-xl text-text-secondary leading-relaxed"
        >
          Join the AlgoText Affiliate Program. Share your unique link and earn 30% recurring revenue on all trading fees generated by users you refer.
        </motion.p>
        <motion.button 
          initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: 0.3 }}
          className="rounded-full bg-accent-green px-10 py-5 text-xl font-bold text-bg-primary shadow-[0_0_40px_rgba(34,197,94,0.3)] transition-transform hover:scale-105"
        >
          Generate My Link Now
        </motion.button>
      </section>

      {/* Interactive Earnings Calculator */}
      <section className="mx-auto max-w-[800px] px-6 py-12">
        <div className="rounded-[2rem] border border-bg-border bg-bg-surface p-10 md:p-16 text-center shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-accent-blue to-accent-green" />
          
          <h3 className="mb-8 text-2xl font-bold text-text-primary">Estimate Your Earnings</h3>
          
          <div className="mb-12">
            <div className="flex justify-between text-sm font-bold text-text-secondary mb-4">
              <span>10 Referrals</span>
              <span>1000 Referrals</span>
            </div>
            <input 
              type="range" 
              min="10" max="1000" step="10"
              value={referrals}
              onChange={(e) => setReferrals(parseInt(e.target.value))}
              className="w-full h-2 bg-bg-primary rounded-lg appearance-none cursor-pointer accent-accent-green"
            />
            <div className="mt-4 text-accent-blue font-bold text-xl">{referrals} Active Traders</div>
          </div>

          <div className="flex flex-col items-center justify-center rounded-2xl bg-[#0a0a0a] p-8 border border-white/5">
            <span className="text-sm font-bold uppercase tracking-wider text-text-secondary mb-2">Estimated Monthly Passive Income</span>
            <span className="text-6xl font-bold text-accent-green">${monthlyEarnings.toLocaleString()}</span>
            <span className="text-xs text-text-tertiary mt-4">Based on average network trading volume. Results may vary.</span>
          </div>
        </div>
      </section>

      {/* How it works (Bento Grid) */}
      <section className="mx-auto max-w-[1200px] px-6 py-20">
        <h2 className="mb-12 text-center text-4xl font-bold text-text-primary">How It Works</h2>
        <div className="grid gap-6 md:grid-cols-3">
          <div className="rounded-3xl border border-bg-border bg-bg-surface p-8">
            <div className="mb-6 flex h-14 w-14 items-center justify-center rounded-2xl bg-accent-blue/10">
              <LinkIcon className="h-7 w-7 text-accent-blue" />
            </div>
            <h3 className="mb-3 text-xl font-bold text-text-primary">1. Get Your Link</h3>
            <p className="text-text-secondary leading-relaxed">Instantly generate your unique on-chain tracking link by connecting your Web3 wallet. No approval process required.</p>
          </div>
          <div className="rounded-3xl border border-bg-border bg-bg-surface p-8">
            <div className="mb-6 flex h-14 w-14 items-center justify-center rounded-2xl bg-purple-500/10">
              <Users className="h-7 w-7 text-purple-500" />
            </div>
            <h3 className="mb-3 text-xl font-bold text-text-primary">2. Share & Refer</h3>
            <p className="text-text-secondary leading-relaxed">Share your link with your audience, trading community, or friends. They get a 10% discount on their first month of fees.</p>
          </div>
          <div className="rounded-3xl border border-bg-border bg-bg-surface p-8 relative overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-br from-accent-green/5 to-transparent pointer-events-none" />
            <div className="mb-6 flex h-14 w-14 items-center justify-center rounded-2xl bg-accent-green/10">
              <DollarSign className="h-7 w-7 text-accent-green" />
            </div>
            <h3 className="mb-3 text-xl font-bold text-text-primary">3. Earn Forever</h3>
            <p className="text-text-secondary leading-relaxed">Whenever your referrals execute a trade, 30% of the platform fee is instantly routed to your wallet via smart contract.</p>
          </div>
        </div>
      </section>
    </div>
  )
}
