"use client"

import * as React from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Users, DollarSign, Activity, ArrowRight, Link as LinkIcon, Gift, CheckCircle2, TrendingUp, Shield, Zap, X, ChevronDown, ChevronUp } from "lucide-react"
import { BackButton } from "@/components/ui/BackButton"

// Mock data for ticker
const recentPayouts = [
  { user: "0x7F...3a1", amount: "$4,250", time: "2 mins ago" },
  { user: "0x2B...9c4", amount: "$1,120", time: "15 mins ago" },
  { user: "0x9A...4d2", amount: "$8,400", time: "1 hour ago" },
  { user: "0x1C...7e5", amount: "$350", time: "2 hours ago" },
  { user: "0x5D...1f8", amount: "$12,050", time: "3 hours ago" },
];

const faqs = [
  { question: "How and when do I get paid?", answer: "Payouts are processed automatically at the end of each month via smart contract directly to your connected Web3 wallet. There is no minimum payout threshold." },
  { question: "Do I need to be a trader to join?", answer: "No! Whether you're a content creator, community manager, or just someone with a large network, you can join and earn from referrals." },
  { question: "How long do I earn from a referral?", answer: "You earn a percentage of their trading fees for life. As long as they keep trading on AlgoText, you keep earning." },
  { question: "Can I track my referrals' performance?", answer: "Yes, our affiliate dashboard provides real-time analytics on your clicks, sign-ups, and the trading volume generated by your referrals." }
];

export default function AffiliatesPage() {
  const [referrals, setReferrals] = React.useState(50)
  const [isModalOpen, setIsModalOpen] = React.useState(false)
  const [openFaq, setOpenFaq] = React.useState<number | null>(null)
  
  // Simulated dynamic calculation
  const monthlyEarnings = referrals * 15 // Assuming average $15/mo revenue share per user (30% of $50)

  return (
    <div className="min-h-screen bg-bg-primary pt-2 pb-32 overflow-hidden relative">
      {/* Background elements */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[500px] bg-accent-green/5 blur-[120px] pointer-events-none rounded-full" />
      
      {/* Hero */}
      <section className="mx-auto max-w-[1000px] px-6 pt-2 pb-16 text-center relative z-10">
        <div className="flex justify-start mb-2"><BackButton /></div>
        <motion.div 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
          className="mb-6 inline-flex items-center gap-2 rounded-full border border-accent-green/30 bg-accent-green/10 px-4 py-1.5 text-sm font-semibold text-accent-green backdrop-blur-sm"
        >
          <Gift className="h-4 w-4" /> Partner Program v2.0 Now Live
        </motion.div>
        <motion.h1 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
          className="mb-6 text-5xl font-extrabold text-text-primary md:text-7xl tracking-tight leading-tight"
        >
          Turn your influence into <br/>
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-accent-green to-emerald-400">Lifelong Revenue</span>
        </motion.h1>
        <motion.p 
          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
          className="mx-auto mb-8 max-w-[650px] text-xl text-text-secondary leading-relaxed"
        >
          Join the elite network of AlgoText partners. Share your unique link and earn up to <span className="text-accent-green font-bold">40% recurring revenue</span> on all subscription fees generated by your community.
        </motion.p>
        <motion.button 
          onClick={() => setIsModalOpen(true)}
          initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: 0.3 }}
          className="rounded-full bg-accent-green px-10 py-4 text-xl font-bold text-bg-primary shadow-[0_0_40px_rgba(34,197,94,0.4)] transition-all hover:scale-105 hover:shadow-[0_0_60px_rgba(34,197,94,0.6)] flex items-center gap-3 mx-auto"
        >
          Apply to Partner Program <ArrowRight className="h-5 w-5" />
        </motion.button>
      </section>

      {/* Payouts Ticker */}
      <section className="w-full border-y border-bg-border bg-bg-surface/50 py-4 mb-20 overflow-hidden relative z-10 flex">
        <div className="flex whitespace-nowrap animate-marquee">
          {[...recentPayouts, ...recentPayouts, ...recentPayouts].map((payout, i) => (
            <div key={i} className="flex items-center gap-3 mx-8">
              <div className="w-2 h-2 rounded-full bg-accent-green animate-pulse" />
              <span className="text-text-secondary font-mono text-sm">{payout.user}</span>
              <span className="text-text-secondary text-sm">earned</span>
              <span className="text-accent-green font-bold text-sm">{payout.amount}</span>
              <span className="text-text-tertiary text-xs ml-2">{payout.time}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Tiers Section */}
      <section className="mx-auto max-w-[1200px] px-6 py-12 relative z-10">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-text-primary mb-4">Rewarding Your Growth</h2>
          <p className="text-xl text-text-secondary max-w-[600px] mx-auto">As your network grows, so do your benefits. Climb the tiers to unlock higher rev-share and exclusive perks.</p>
        </div>
        <div className="grid md:grid-cols-3 gap-8">
          {[
            { name: "Silver", share: "20%", volume: "< 50 Referrals", perks: ["Real-time dashboard", "Standard support", "Monthly payouts"], color: "bg-slate-400", glow: "shadow-[0_0_30px_rgba(148,163,184,0.1)]" },
            { name: "Gold", share: "30%", volume: "50 - 250 Referrals", perks: ["Custom tracking links", "Priority support", "Bi-weekly payouts", "Marketing assets"], color: "bg-yellow-400", glow: "shadow-[0_0_40px_rgba(250,204,21,0.15)] border-yellow-400/30", featured: true },
            { name: "Diamond", share: "40%", volume: "250+ Referrals", perks: ["Dedicated account manager", "Weekly payouts", "Custom API integration", "VIP Event invites"], color: "bg-cyan-400", glow: "shadow-[0_0_30px_rgba(34,211,238,0.1)]" }
          ].map((tier, i) => (
            <div key={i} className={`rounded-[2rem] border border-bg-border bg-bg-surface p-8 relative flex flex-col transition-all hover:-translate-y-2 ${tier.glow} ${tier.featured ? 'md:-translate-y-4 md:hover:-translate-y-6' : ''}`}>
              {tier.featured && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-yellow-400 text-black px-4 py-1 text-xs font-bold rounded-full">MOST POPULAR</div>
              )}
              <h3 className="text-2xl font-bold text-text-primary mb-2 flex items-center gap-2">
                <div className={`w-3 h-3 rounded-full ${tier.color}`} /> {tier.name}
              </h3>
              <div className="mb-6 pb-6 border-b border-bg-border/50">
                <div className="text-5xl font-extrabold text-text-primary mb-2">{tier.share}</div>
                <div className="text-text-secondary text-sm">Revenue Share</div>
                <div className="mt-4 text-sm font-medium text-text-secondary bg-bg-primary inline-block px-3 py-1 rounded-lg">{tier.volume}</div>
              </div>
              <ul className="space-y-4 mb-8 flex-1">
                {tier.perks.map((perk, j) => (
                  <li key={j} className="flex items-start gap-3 text-text-secondary">
                    <CheckCircle2 className={`h-5 w-5 shrink-0 ${tier.featured ? 'text-yellow-400' : 'text-accent-green'}`} />
                    <span>{perk}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </section>

      {/* Interactive Earnings Calculator */}
      <section className="mx-auto max-w-[800px] px-6 py-20 relative z-10">
        <div className="rounded-[2.5rem] border border-bg-border bg-bg-surface/80 backdrop-blur-xl p-10 md:p-16 text-center shadow-2xl relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-accent-blue via-accent-green to-emerald-400" />
          <div className="absolute -inset-24 bg-gradient-to-tr from-accent-green/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none" />
          
          <h3 className="mb-4 text-3xl font-bold text-text-primary">Estimate Your Earnings</h3>
          <p className="mb-12 text-text-secondary">Slide to see how much you could earn with our Gold tier (30% share).</p>
          
          <div className="mb-14 relative">
            <div className="flex justify-between text-sm font-bold text-text-secondary mb-6">
              <span>10 Referrals</span>
              <span>1000 Referrals</span>
            </div>
            <input 
              type="range" 
              min="10" max="1000" step="10"
              value={referrals}
              onChange={(e) => setReferrals(parseInt(e.target.value))}
              className="w-full h-3 bg-bg-primary rounded-full appearance-none cursor-pointer accent-accent-green shadow-inner"
            />
            <div className="mt-8 text-accent-green font-bold text-2xl flex items-center justify-center gap-2">
              <Users className="h-6 w-6" /> {referrals} Active Subscribers
            </div>
          </div>

          <div className="flex flex-col items-center justify-center rounded-3xl bg-[#050505] p-10 border border-white/10 shadow-inner relative overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-b from-accent-green/10 to-transparent pointer-events-none" />
            <span className="text-sm font-bold uppercase tracking-widest text-text-secondary mb-4 flex items-center gap-2">
              <TrendingUp className="h-4 w-4" /> Estimated Monthly Income
            </span>
            <span className="text-7xl font-extrabold text-transparent bg-clip-text bg-gradient-to-br from-white to-accent-green drop-shadow-sm">
              ${monthlyEarnings.toLocaleString()}
            </span>
            <span className="text-sm text-text-tertiary mt-6 max-w-[300px]">Based on an average $50/mo subscription fee across your referrals.</span>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="mx-auto max-w-[800px] px-6 py-20 relative z-10">
        <h2 className="mb-12 text-center text-4xl font-bold text-text-primary">Frequently Asked Questions</h2>
        <div className="space-y-4">
          {faqs.map((faq, i) => (
            <div key={i} className="border border-bg-border rounded-2xl bg-bg-surface overflow-hidden">
              <button 
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
                className="w-full px-6 py-5 flex items-center justify-between text-left font-bold text-lg text-text-primary hover:bg-white/5 transition-colors"
              >
                {faq.question}
                {openFaq === i ? <ChevronUp className="h-5 w-5 text-text-secondary" /> : <ChevronDown className="h-5 w-5 text-text-secondary" />}
              </button>
              <AnimatePresence>
                {openFaq === i && (
                  <motion.div 
                    initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }}
                    className="overflow-hidden"
                  >
                    <div className="px-6 pb-5 text-text-secondary leading-relaxed">
                      {faq.answer}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </section>

      {/* Google Form Modal */}
      <AnimatePresence>
        {isModalOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center px-4">
            <motion.div 
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              onClick={() => setIsModalOpen(false)}
              className="absolute inset-0 bg-black/80 backdrop-blur-sm"
            />
            <motion.div 
              initial={{ opacity: 0, scale: 0.95, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="relative w-full max-w-[700px] bg-bg-surface border border-bg-border rounded-[2rem] overflow-hidden shadow-2xl flex flex-col h-[85vh] max-h-[800px]"
            >
              <div className="p-6 border-b border-bg-border flex justify-between items-center bg-bg-primary/50 relative z-10">
                <h3 className="text-xl font-bold text-text-primary flex items-center gap-2">
                  <Gift className="h-5 w-5 text-accent-green" /> Partner Application
                </h3>
                <button 
                  onClick={() => setIsModalOpen(false)}
                  className="p-2 rounded-full hover:bg-white/10 transition-colors text-text-secondary"
                >
                  <X className="h-5 w-5" />
                </button>
              </div>
              <div className="flex-1 overflow-hidden bg-white/5 relative">
                <iframe 
                  src="https://docs.google.com/forms/d/e/1FAIpQLScX0T9v5x4xZ6j3_p_Y_p_Y_p_Y_p_Y_p_Y_p_Y_p_Y_p_Y/viewform?embedded=true" 
                  width="100%" 
                  height="100%" 
                  frameBorder="0" 
                  marginHeight={0} 
                  marginWidth={0}
                  className="w-full h-full bg-white"
                >
                  Loading…
                </iframe>
                
                {/* Fallback overlay in case the form ID is broken / not replaced yet */}
                <div className="absolute inset-0 pointer-events-none flex flex-col items-center justify-center bg-bg-surface/80 backdrop-blur-sm z-20 opacity-0 hover:opacity-100 transition-opacity">
                  <div className="bg-bg-primary p-6 rounded-2xl border border-bg-border text-center max-w-sm pointer-events-auto shadow-2xl">
                    <Users className="h-10 w-10 text-accent-green mx-auto mb-4" />
                    <h4 className="text-lg font-bold text-text-primary mb-2">Google Form Setup</h4>
                    <p className="text-text-secondary text-sm mb-4">
                      Replace the iframe src URL in <code className="text-accent-green bg-accent-green/10 px-1 py-0.5 rounded">src/app/affiliates/page.tsx</code> with your real Google Form embed link.
                    </p>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
      
      <style>{`
        @keyframes marquee {
          0% { transform: translateX(0%); }
          100% { transform: translateX(-50%); }
        }
        .animate-marquee {
          animation: marquee 40s linear infinite;
          width: max-content;
        }
        .animate-marquee:hover {
          animation-play-state: paused;
        }
      `}</style>
    </div>
  )
}

