import * as React from "react"
import { BackButton } from "@/components/ui/BackButton"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg-primary pt-2 pb-32">
      <div className="mx-auto max-w-[800px] px-6 py-12">
        <BackButton />
        <h1 className="mb-4 text-4xl font-bold text-text-primary tracking-tight">Terms of Service</h1>
        <p className="mb-12 text-text-secondary">Last Updated: October 15, 2026</p>

        <div className="prose prose-invert max-w-none text-text-secondary">
          <h3 className="text-xl font-bold text-text-primary mb-4">1. Acceptance of Terms</h3>
          <p className="mb-8 leading-relaxed">
            By accessing or using the AlgoText platform ("Service"), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the Service. AlgoText provides a non-custodial software interface that allows users to construct, backtest, and deploy algorithmic trading strategies.
          </p>

          <h3 className="text-xl font-bold text-text-primary mb-4">2. Non-Custodial Nature</h3>
          <p className="mb-8 leading-relaxed">
            AlgoText is strictly a non-custodial technology provider. We do not hold, control, or have direct access to your digital assets. All live trading execution is facilitated through smart contract approvals granted by your self-hosted Web3 wallet. You are solely responsible for securing your private keys and seed phrases.
          </p>

          <h3 className="text-xl font-bold text-text-primary mb-4">3. Risk Disclosure</h3>
          <p className="mb-8 leading-relaxed">
            Trading cryptocurrencies involves significant risk and can result in the loss of your invested capital. You should not invest more than you can afford to lose. The backtesting results, strategies generated by our AI models, and any other data provided by AlgoText do not constitute financial advice. Past performance is not indicative of future results.
          </p>

          <h3 className="text-xl font-bold text-text-primary mb-4">4. Fees and Payments</h3>
          <p className="mb-8 leading-relaxed">
            AlgoText charges a flat execution fee of 0.05% on the notional volume of trades executed live through the platform. This fee is deducted automatically at the time of execution. We reserve the right to modify our fee structure with a 30-day prior notice provided via the platform or email.
          </p>

          <h3 className="text-xl font-bold text-text-primary mb-4">5. Intellectual Property</h3>
          <p className="mb-8 leading-relaxed">
            The Service and its original content (excluding User-Generated Strategies), features, and functionality are and will remain the exclusive property of AlgoText Inc and its licensors. You retain full ownership of the unique algorithmic strategies you construct using our platform.
          </p>
        </div>
      </div>
    </div>
  )
}
